inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-discourse: default.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドの行数制限
MethodLength:
  Max: 50

# メソッドの複雑度の制限
CyclomaticComplexity:
  Max: 11
PerceivedComplexity:
  Max: 11