source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'rails',                      '6.1.4'
gem 'mysql2',                     '~> 0.5'
gem 'puma',                       '~> 5.0'
gem 'bootsnap',                   '>= 1.4.4', require: false
gem 'rack-cors',                  '1.1.1'
gem 'devise',                     '4.8.0'
gem 'devise_token_auth',          '1.2.0'
gem 'devise-i18n',                '1.10.1'
gem 'active_storage_validations', '0.9.6'
gem 'aws-sdk-s3',                 '1.111.3', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails',       '5.1.0'
  gem 'rubocop',           '1.25.1', require: false
  gem 'rubocop-rails',     '2.13.2', require: false
  gem 'rubocop-rspec',     '2.8.0',  require: false
  gem 'rubocop-discourse', '2.5.0',  require: false
  gem 'pry-rails',         '0.3.9'
  gem 'factory_bot_rails', '6.2.0'
  gem 'faker',             '2.19.0'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
