source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'rails',  '6.1.4'
gem 'mysql2', '~> 0.5'
gem 'puma',   '~> 5.0'
# gem 'image_processing', '~> 1.2'
gem 'bootsnap',          '>= 1.4.4', require: false
gem 'rack-cors',         '1.1.1'
gem 'devise',            '4.8.0'
gem 'devise_token_auth', '1.2.0'
gem 'devise-i18n',       '1.10.1'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails',       '5.1.0'
  gem 'rubocop',           '1.25.1', require: false
  gem 'rubocop-rails',     '2.13.2', require: false
  gem 'rubocop-rspec',     '2.8.0',  require: false
  gem 'rubocop-discourse', '2.5.0',  require: false
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
