variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "AWS_REGION" {}
variable "FRONT_CONTAINER_NAME" {}
variable "BACK_CONTAINER_NAME" {}
variable "AWS_ACCOUNT_ID" {}
variable "RAILS_MASTER_KEY" {}
variable "DB_PASSWORD" {}
variable "DB_USERNAME" {}
variable "GOOGLE_API_KEY" {}
